name: Publish

on:
  push:
    tags: ["v*.*.*"]

permissions:
  contents: read
  id-token: write

jobs:
  publish:
    runs-on: ubuntu-24.04
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}
      - name: Set up pnpm and Node.js
        uses: ./.github/actions/setup-pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build library
        run: pnpm build

      - name: Publish package
        run: npm publish --access public
